"""
Pydantic models for alerts from swarm agents
"""

from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime
from shared.schemas.detection import Detection


class Alert(BaseModel):
    """Alert generated by swarm agents"""
    id: str = Field(description="Unique alert ID")
    timestamp: float = Field(description="Unix timestamp of alert")
    type: str = Field(description="Alert type (e.g., 'object_detection', 'gesture_command')")
    severity: Literal["low", "medium", "high", "critical"] = Field(
        description="Alert severity level"
    )
    description: str = Field(description="Human-readable alert description")
    detection: Optional[Detection] = Field(
        default=None,
        description="Original detection from Jetson edge"
    )
    source: Literal["jetson", "swarm"] = Field(
        description="Source of alert (jetson = raw, swarm = refined)"
    )
    payment_status: Optional[Literal["pending", "confirmed", "failed"]] = Field(
        default=None,
        description="x402 payment status"
    )
    payment_tx_id: Optional[str] = Field(
        default=None,
        description="Solana transaction ID for payment"
    )
    payment_amount: Optional[float] = Field(
        default=None,
        description="Payment amount in USDC"
    )
    context: Optional[dict] = Field(
        default=None,
        description="Context analysis from swarm agents"
    )
    swarm_confidence: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Swarm confidence score (0-1)"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "alert-123",
                "timestamp": 1699123456.789,
                "type": "object_detection",
                "severity": "high",
                "description": "Person detected with weapon",
                "source": "swarm",
                "payment_status": "confirmed",
                "payment_tx_id": "5j7s8K9...",
                "payment_amount": 0.01,
                "swarm_confidence": 0.87
            }
        }
